# Generated by Django 3.2 on 2025-03-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=56, verbose_name='Breed Name')),
                ('life_expectancy', models.CharField(max_length=56, verbose_name='Life Expectancy')),
                ('cat_size', models.CharField(max_length=56, verbose_name='Cat Size')),
                ('weight_of_the_cat', models.CharField(max_length=56, verbose_name='Weight (kg)')),
                ('cat_size_1', models.CharField(max_length=56, verbose_name='Care Instructions')),
                ('care', models.CharField(max_length=56, verbose_name='Care Instructions')),
                ('personality', models.CharField(max_length=56, verbose_name='Personality')),
                ('activity', models.CharField(max_length=56, verbose_name='Activity Level')),
                ('image', models.ImageField(blank=True, help_text='Загрузите репрезентативное изображение породы.', null=True, upload_to='cat_images/', verbose_name='Картинка')),
                ('Wool', models.CharField(max_length=56, verbose_name='Wool Type')),
                ('Molting', models.CharField(max_length=56, verbose_name='Molting Level')),
                ('Attitude_towards_children', models.CharField(max_length=56, verbose_name='Attitude Towards Children')),
                ('Attitude_towards_other_animals', models.CharField(max_length=56, verbose_name='Attitude Towards Other Animals')),
                ('The_level_of_intelligence', models.CharField(max_length=56, verbose_name='Intelligence Level')),
                ('The_need_for_attention', models.CharField(max_length=56, verbose_name='Need for Attention')),
                ('Nutrition_features', models.CharField(max_length=56, verbose_name='Nutritional Features')),
            ],
            options={
                'verbose_name': 'Порода кошек',
                'verbose_name_plural': 'Породы кошек',
                'ordering': ['breed'],
            },
        ),
    ]
